# Copyright (c) 2019 Mattia Maragno
# Composer File Servizi interni
version: '3.7'
services:
##########CONTAINER REVERSE PROXY NGINX
#CONTAINER REVERSE-PROXY
    reverseprx:
        image: jwilder/nginx-proxy:alpine
        labels:
          - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
        container_name: reverseprx
        ports:
          - '80:80/tcp'
          - '443:443/tcp'
        volumes:
            - /DockerV_fe/reverseprx/conf.d:/etc/nginx/conf.d:rw
            - /DockerV_fe/reverseprx/vhost.d:/etc/nginx/vhost.d:rw
            - /DockerV_fe/reverseprx/html:/usr/share/nginx/html:rw
            - /DockerV_fe/reverseprx/certs:/etc/nginx/certs:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: always
        networks:
           - net_wifi

#CONTAINER FOR SSL CERTIFICATE
    sslmanager:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: sslmanager
        volumes:
            - /DockerV_fe/reverseprx/vhost.d:/etc/nginx/vhost.d:rw
            - /DockerV_fe/reverseprx/html:/usr/share/nginx/html:rw
            - /DockerV_fe/reverseprx/certs:/etc/nginx/certs:rw
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: always
        links:
            - reverseprx
        networks:
           - net_wifi

#CONTAINER FOR UBIQUITI WIFI
#CERTIFICATO SSL ATTIVATO
    unifi:
        restart: always
        container_name: unifi
        ports:
            - "3478:3478/udp"
            - "6789:6789/tcp"
            - "8080:8080/tcp"
            - "8443:8443/tcp"
            - "8880:8880/tcp"
            - "8843:8843/tcp"
            - "10001:10001/udp"
        environment:
            - TZ=Europe/Rome
            - VIRTUAL_HOST=EXTERNAL_DNS_NAME
            - LETSENCRYPT_HOST=EXTERNAL_DNS_NAME
            - LETSENCRYPT_EMAIL=CHANGE_WITHYOUR_EMAL
        volumes:
            - /DockerV_unifi:/unifi
            - /DockerV_unifi_cert:/unifi/cert
        image: 'jacobalberty/unifi'
        networks:
            - net_wifi

#MAPPING RETI ESISTENTI
networks:
 net_wifi:
  external: true

